### ISSUE TITLE
Problem with the latest update of the chrome-remote-desktop package 

### ISSUE THREAD

**Issue by googleg** [cardinalby/chrome-remote-desktop-image#7]
Just a quick note to mention that the latest upgrade of the chrome-remote-desktop linux package has a bug that prevents the remote desktop server from starting. 

There is a problem with the file /opt/google/chrome-remote-desktop/chrome-remote-desktop. This is a Python script that cannot be executed:

```
 python3 chrome-remote-desktop
  File "chrome-remote-desktop", line 649
    as infile,
    ^
 SyntaxError: invalid syntax
```

I am happy to confirm that there is a work-around which is overwriting the faulty script /opt/google/chrome-remote-desktop/chrome-remote-desktop with an earlier version.

I did not notice any obvious side effect of using an older script, for now.

I do not think I can add the working version of the file here as it is licensed by Google. We'll have to wait for them to fix the problem I guess.

**Comment by cardinalby** [comment]
Thanks for the information!

So, you don't recommend rebuilding & republishing the image if I'm right, because the version in the image seems to work?

The image uses https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb link to download the package during build process. Maybe you are aware of a link that can be used to pin the exact version?

**Comment by googleg** [comment]
You are 100% correct the image uses a link to the latest version, so at build time the latest available version is pulled and embedded. 

Unfortunately Google does not publish direct links but if you know the version you are looking for you can use this link: https://dl.google.com/linux/chrome-remote-desktop/deb/pool/main/c/chrome-remote-desktop/chrome-remote-desktop_${VERSION}_amd64.deb

For example the latest working version was 116.0.5845.9 which can be found here: https://dl.google.com/linux/chrome-remote-desktop/deb/pool/main/c/chrome-remote-desktop/chrome-remote-desktop_116.0.5845.9_amd64.deb

Also I've found a mirror that keeps history of old versions: https://deb.rug.nl/ppa/mirror/dl.google.com/linux/chrome-remote-desktop/deb/pool/main/c/chrome-remote-desktop/

So for now to avoid problems do not rebuild the image nor update the package chrome-remote-desktop from within a running container.

**Comment by googleg** [comment]
Sure, I'll keep you posted. I have raised the issue to Google, not that I am expecting an answer but hopefully this will help them realize they made a snafu.

**Comment by googleg** [comment]
Quick update: Google has published a new version of the package, 116.0.5845.10, which fixes one problem in the code but there is another bug in the code that still prevents the service to start properly.

I have reported it once again, let's see if they can finally fix it.

I have the impression they are not testing before releasing, quite scary.

**Comment by googleg** [comment]
Ok folks, good news, the problem seems to have been fixed in the latest update of the package released on 29th September:

chrome-remote-desktop_118.0.5993.9_amd64.deb

I am closing the issue.

**Comment by cardinalby** [comment]
Thanks for the update
